### ISSUE TITLE
MacOS Not working

### ISSUE THREAD

**Issue by finnschi** [cg2121/obs-decklink-output-filter#3]
```
10:10:24.771:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-decklink-output-filter/bin/obs-decklink-output-filter.so
10:10:24.771:   Reason: image not found
10:10:24.771: 
10:10:24.771: Module '/Library/Application Support/obs-studio/plugins/obs-decklink-output-filter/bin/obs-decklink-output-filter.so' not loaded
```
on MacOS BigSur with OBS 27.1.3

**Comment by MJTPDMZ** [comment]
This plug-in is just what I need, but I have the same problem on two computers: MacOS BigSur with OBS 27.2.4 and MacOS Monterey with OBS 27.2.4

**Comment by cg2121** [comment]
Should be working with latest release https://github.com/cg2121/obs-decklink-output-filter/releases/tag/1.1.0

**Comment by MJTPDMZ** [comment]
Unfortunatly, it's still not working. Filter does not show up in the list of available filters. Tested on both a Intel and a M1 Mac.
